# Generated by Django 6.0.5 on 2026-06-02 20:39

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О компании', max_length=200)),
                ('about_text', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('video_url', models.URLField(blank=True)),
                ('requisites', models.TextField(blank=True, help_text='Реквизиты организации')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('duties', models.TextField()),
                ('phone', models.CharField(max_length=24, validators=[core.validators.validate_belarus_phone])),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['-created_at_utc'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Одно предложение', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('full_text', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24, validators=[core.validators.validate_belarus_phone])),
                ('birth_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('discount_percent', models.PositiveSmallIntegerField(default=5)),
                ('is_archived', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'ordering': ['-is_archived', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24, validators=[core.validators.validate_belarus_phone])),
                ('birth_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('event', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.companyinfo')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(default='Коммерческий отдел', max_length=100)),
                ('phone', models.CharField(max_length=24, validators=[core.validators.validate_belarus_phone])),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('characteristics', models.TextField(help_text='Площадь, этаж, район и т.д.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_active', models.BooleanField(default=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='properties', to='core.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.category')),
                ('owners', models.ManyToManyField(blank=True, related_name='properties', to='core.owner')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_utc'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sale_date', models.DateField()),
                ('contract_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.buyer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.property')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_utc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at_local', models.DateTimeField(blank=True, editable=False, null=True)),
                ('timezone', models.CharField(default='Europe/Minsk', max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, validators=[core.validators.validate_belarus_phone])),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Сотрудник')], default='client', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
