# Generated by Django 5.2.15 on 2026-06-03 21:17

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания, к которой относится новость.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.companyinfo', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at_local_text',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at_timezone',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default=core.models.default_user_timezone, max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterUniqueTogether(
            name='companyhistory',
            unique_together={('company', 'year')},
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Картинка')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок показа')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная картинка')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Картинка объекта недвижимости',
                'verbose_name_plural': 'Картинки объектов недвижимости',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('property', 'sort_order')},
            },
        ),
    ]
